name: "Scan IP"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IP_HOST: scanme.nmap.org

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: "MTES-MCT/nmap-action@main"
        with:
          host: $IP_HOST
          outputDir: 'scans'
          outputFile: 'nmapvuln.json'
          raw: false
          withVulnerabilities: true