name: "Scan IP"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  scan_ip:
    env:
      IP_HOST: 'scanme.nmap.org'
    runs-on: ubuntu-latest
    steps:
      - uses: "MTES-MCT/nmap-action@main"
        with:
          host: ${{env.IP_HOST}}
          outputDir: 'scans'
          outputFile: 'nmapvuln.json'
          raw: false
          withVulnerabilities: true